name: Django CI

on:
  push:
    branches: [main, account,event]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: smartvillage_db
          POSTGRES_USER: smartvillage_user
          POSTGRES_PASSWORD: smartvillage_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U smartvillage_user -d smartvillage_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_NAME: smartvillage_db
      DATABASE_USER: smartvillage_user
      DATABASE_PASSWORD: smartvillage_pass
      DATABASE_HOST: postgres   # service name matches above
      DATABASE_PORT: 5432
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Run Django tests with coverage
        run: |
          coverage run manage.py test
          coverage report --fail-under=85
          coverage xml

